apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-nodejs1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-nodejs1
  template:
    metadata:
      labels:
        app: gke-nodejs1
    spec:
      containers:
      - name: nodejs
        image: gcr.io/indigo-skyline-478417-k4/gke_nodejs:latest
        ports:
        - containerPort: 8080
